spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_channel?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 588686
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    map-underscore-to-camel-case: true
server:
  port: 8001
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0

